config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'links#index'

  resources :links

  get '/:tag', to: 'links#by_tag', as: 'links_by_tag'

  devise_for :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    return unless user && user.admin?
    can :access, :rails_admin
    can :read, :dashboard
    can :manage, :all
  end
end

app/models/link.rb
class Link
  include Mongoid::Document

  belongs_to :user

  field :url, type: String
  field :tags, type: String
  field :description, type: String

  validates :url, presence: true

  before_create :format_tags

  def format_tags
    array = Array.new
    self.tags.downcase.gsub(/[a-z0-9]+/).each { |word| array << word }
    self.tags = array.join(',')
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include SimpleEnum::Mongoid
  
  has_many :links
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""
  as_enum :role, admin: 'Admin', user: 'User'

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String


  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_link, only: [:show, :edit, :update, :destroy]


  # GET /links
  def index
    @links = Link.where(user_id: current_user.id)
  end

  # GET /links/1
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  def create
    @link = Link.new(link_params)

    if @link.save
      redirect_to root_url, notice: 'Link was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /links/1
  def update
    if @link.update(link_params)
      redirect_to root_url, notice: 'Link was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /links/1
  def destroy
    @link.destroy

    redirect_to links_url
  end

  # GET /links/sport
  def by_tag
    @links = Link.where(tags: /(#{params[:tag].lstrip})/, user_id: current_user.id)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_link
    @link = Link.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def link_params
    params.require(:link).permit(:url, :tags, :description).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title WebmilTest
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'partials/header'
    = yield

app/views/links/_form.html.haml
= form_for @link do |f|
  - if @link.errors.any?
    #error_explanation
      %h2= "#{pluralize(@link.errors.count, "error")} prohibited this link from being saved:"
      %ul
        - @link.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :tags
    = f.text_field :tags
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/links/by_tag.html.haml
%h1
  = params[:tag]

%table
  %thead
    %tr
      %th Url
      %th Tags
      %th Description
      %th
      %th
      %th

  %tbody
    - @links.each do |link|
      %tr
        %td= link.url
        %td
          - link.tags.split(',').each do |tag|
            = link_to "##{tag.strip}", links_by_tag_path(tag)
        %td= link.description
        %td= link_to 'Show', link
        %td= link_to 'Edit', edit_link_path(link)
        %td= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' }

%br

app/views/links/edit.html.haml
%h1 Editing link

= render 'form'

= link_to 'Show', @link
\|
= link_to 'Back', links_path

app/views/links/index.html.haml
%h1 Listing links

%table
  %thead
    %tr
      %th Url
      %th Tags
      %th Description
      %th
      %th
      %th

  %tbody
    - @links.each do |link|
      %tr
        %td= link.url
        %td
          - link.tags.split(',').each do |tag|
            = link_to "#{tag.strip}", links_by_tag_path(tag)
        %td= link.description
        %td= link_to 'Show', link
        %td= link_to 'Edit', edit_link_path(link)
        %td= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Link', new_link_path

app/views/links/new.html.haml
%h1 New link

= render 'form'

= link_to 'Back', links_path

app/views/links/show.html.haml
%p#notice= notice

%p
  %b Url:
  = @link.url
%p
  %b Tags:
  - @link.tags.each do |tag|
    = link_to "##{tag}", links_by_tag_path(tag)
%p
  %b Description:
  = @link.description

= link_to 'Edit', edit_link_path(@link)
\|
= link_to 'Back', links_path

app/views/partials/_header.html.haml
.auth
  - if !user_signed_in?
    = link_to 'Sign In', new_user_session_path
    = link_to 'Sign Up', new_user_registration_path
  - else
    = link_to 'Sign Out', destroy_user_session_path, method: :delete